#!/bin/bash
# Builds the Habitat EasyFlash CRT cartridge image + zip.

set -ueo pipefail

cat << EOF > ./docker-compose.yml
---
version: '3'
services:
  habiclient:
    build: .
    platform: linux/amd64
    image: philcollins/habiclient
    command: bash -c 'export CC65_HOME=/usr/share/cc65 && make clean && make cart'
    volumes:
      - .:/habiclient
EOF

docker compose up

rm -f ./docker-compose.yml
